# -*- coding: utf-8 -*-
"""week_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mhHJFT2JMA98gB4kCcDgNF9CUbRHIx2_
"""

import pandas as pd
import numpy as np

data = pd.read_csv("week2Data.csv")
print(data)

concepts = np.array(data.iloc[:,1:-1])
target = np.array(data.iloc[:,-1])
print(concepts)
print(target)

def learn(concepts, target):
    specific_h = concepts[0].copy()
    general_h = [['?' for i in range(len(specific_h))] for j in range(len(specific_h))]
    print("initial general hypothesis and specific hypothises:")
    print("specific_h = ",specific_h)
    print("general_h = ",general_h)

    for i,h in enumerate(concepts):
        if target[i] == "Yes":
            for x in range(len(specific_h)):
                if h[x]!= specific_h[x]:
                    specific_h[x] = '?'
                    general_h[x][x] = '?'
        
        if target[i] == "No":
            for x in range(len(specific_h)):
                if h[x]!= specific_h[x]:
                    general_h[x][x] = specific_h[x]
                else:
                    general_h[x][x] = '?'
        
        print("steps of candidate elimination alg",(i+1))
        print("specific_h = ",specific_h)
        print("general_h = ",general_h)

    indices = [i for i,val in enumerate(general_h) if val ==['?', '?', '?', '?', '?', '?']]
    for i in indices:
        general_h.remove(['?','?', '?', '?', '?', '?'])
    
    return specific_h, general_h


fin_specific_h,fin_general_h =learn(concepts,target)
print("output")
print("specific_h = ",fin_specific_h)
print("general_h = ",fin_general_h)

