# -*- coding: utf-8 -*-
"""week_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xm3QHtqVR6X0Bcu65At7t6R0qigXdPZh
"""

import pandas as pd
import numpy as np

df = pd.read_csv("week1Data.csv")
print("data")
print(df)

a = df.values
print(a)
print("total no.of training instances: ",len(a))
num_attr = len(a[0])-1
print("initial hypothesis:")
hypothesis = ['@']*num_attr
print(hypothesis)

for i in range(len(a)):
    if a[i][num_attr] == "Yes":
        for j in range(num_attr):
            if hypothesis[j]=='@' or hypothesis[j]==a[i][j]:
                hypothesis[j] = a[i][j]
            else:
                hypothesis[j] = '?'
    print("\n The hypothesis for the training instance {} is : \n".format(i+1),hypothesis)
    
print("\n The maximally specific hypotheses for the training instance is:")
print(hypothesis)